"""模型预设配置 API - 管理不同模型的启动参数预设"""
import json
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, field_validator
from app.database import get_conn, now
from app.config import settings

router = APIRouter()


def _normalize_device(v) -> str:
    """设备角色归一化（后端无关语义值）。
    语义值 auto/discrete/integrated 原样保留；具体设备名或旧值映射为语义值：
      SYCL0/Vulkan1 → discrete（独显），SYCL1/Vulkan0 → integrated（核显），旧数字 0→discrete / 1→integrated。
    启动时由 instance_mgr 按当前后端动态解析成具体设备名（SYCL0/Vulkan1）。
    """
    if not v:
        return "auto"
    s = str(v).strip()
    low = s.lower()
    if low in ("auto", "discrete", "integrated"):
        return low
    if s.startswith("SYCL"):
        return "integrated" if s == "SYCL1" else "discrete"
    if s.startswith("Vulkan"):
        return "integrated" if s == "Vulkan0" else "discrete"
    if s.isdigit():
        return "discrete" if s == "0" else "integrated"
    return "auto"


def _find_mmproj(model_name: str) -> str:
    """在模型 gguf 同目录中查找 mmproj 文件（mmproj*.gguf）
    通过 services 表 model_path 定位模型文件所在目录，返回绝对路径或空串"""
    from pathlib import Path as _P
    base = _P(settings.model_dir)
    if not base.exists():
        return ""
    # 1) 通过 services 表拿到 model_path，找同目录
    search_dirs = []
    try:
        with get_conn() as conn:
            row = conn.execute("SELECT model_path FROM services WHERE name=?", (model_name,)).fetchone()
        if row and row["model_path"]:
            mp = row["model_path"].replace("/models/", "")
            p = base / mp
            search_dirs.append(p.parent if p.suffix else p)
    except Exception:
        pass
    # 2) 兜底：模型名是 gguf 文件名时，其目录 = base；否则扫描子目录
    if not search_dirs:
        if base.glob(f"{model_name}.gguf"):
            search_dirs.append(base)
        else:
            for d in base.iterdir():
                if d.is_dir() and d.name in model_name:
                    search_dirs.append(d)
    seen = set()
    for d in search_dirs:
        if not d.exists() or d in seen:
            continue
        seen.add(d)
        for p in sorted(d.glob("*mmproj*.gguf")):
            return str(p)
    return ""


def _write_config_ini() -> dict:
    """从 DB 全量生成 config.ini 并写入模型目录（幂等：先清空再重建）
    返回 {"ok": bool, "path": str, "content": str, "error": str?}
    """
    from pathlib import Path

    with get_conn() as conn:
        rows = conn.execute("SELECT * FROM model_presets ORDER BY model_name").fetchall()
        # 预设名 -> 模型文件路径（services 表），供 config.ini 的 model= 行
        path_rows = conn.execute("SELECT name, model_path FROM services").fetchall()
        path_by_name = {r["name"]: r["model_path"] for r in path_rows}

    lines = ["# llama-server router model presets", "# Auto-generated by llama-studio", ""]
    for r in rows:
        d = dict(r)
        lines.append(f"[{d['model_name']}]")
        # model= 必须显式绑定文件路径，llama.cpp 才会应用该段的 ctx/参数到对应模型
        mp = path_by_name.get(d["model_name"])
        if mp:
            lines.append(f"model = {mp}")
        lines.append(f"ctx-size = {d['ctx_size']}")
        lines.append(f"temp = {d['temp']}")
        lines.append(f"threads = {d['threads']}")
        lines.append(f"batch-size = {d['batch_size']}")
        lines.append(f"ubatch-size = {d['ubatch_size']}")
        lines.append(f"parallel = {d['parallel']}")
        lines.append(f"cache-type-k = {d['cache_type_k']}")
        lines.append(f"cache-type-v = {d['cache_type_v']}")
        if d["flash_attn"]:
            lines.append("flash-attn = on")
        if d["jinja"]:
            lines.append("jinja = on")
        if not d.get("mmap", 1):
            lines.append("no-mmap = on")
        # MoE 专家 offload CPU：0/空=全部专家层（cpu-moe = on）；N>0=仅前 N 层（n-cpu-moe = N）
        if d.get("cpu_moe"):
            _cmoe_n = d.get("cpu_moe_layers") or 0
            if _cmoe_n and _cmoe_n > 0:
                lines.append(f"n-cpu-moe = {_cmoe_n}")
            else:
                lines.append("cpu-moe = on")
        _ngl = d['n_gpu_layers']
        lines.append(f"n-gpu-layers = {('auto' if _ngl is not None and _ngl < 0 else _ngl)}")
        dev = _normalize_device(d.get("device"))
        # 语义值 → 具体设备名（后端无关；解析失败则写回语义值兜底）
        try:
            from app.instance_mgr import _resolve_device
            dev_resolved = _resolve_device(dev)
            if dev_resolved:
                dev = dev_resolved
        except Exception:
            pass
        lines.append(f"device = {dev}")
        # RoPE/YaRN 长上下文缩放（Qwen 社区建议 >32K 必须启用）
        rs = d.get("rope_scaling")
        if rs:
            lines.append(f"rope-scaling = {rs}")
            if d.get("rope_scale"):
                lines.append(f"rope-scale = {d['rope_scale']}")
            if d.get("yarn_orig_ctx"):
                lines.append(f"yarn-orig-ctx = {d['yarn_orig_ctx']}")
        # MTP 草稿 KV cache 量化（默认 f16 浪费显存，建议 q8_0）——仅非空才写，空则用默认
        if d.get("spec_draft_type_k"):
            lines.append(f"spec-draft-type-k = {d['spec_draft_type_k']}")
        if d.get("spec_draft_type_v"):
            lines.append(f"spec-draft-type-v = {d['spec_draft_type_v']}")
        # 思考（Reasoning）：--reasoning on/off/auto + --reasoning-budget N + --reasoning-effort
        reasoning = d.get("reasoning")
        if reasoning:
            lines.append(f"reasoning = {reasoning}")
            if d.get("reasoning_budget") is not None:
                lines.append(f"reasoning-budget = {d['reasoning_budget']}")
            if d.get("reasoning_effort"):
                lines.append(f"reasoning-effort = {d['reasoning_effort']}")
        # 自动检测 mmproj 并写入（多模态投影文件）
        mmproj = _find_mmproj(d["model_name"])
        if mmproj:
            lines.append(f"mmproj = {mmproj}")
        extra = json.loads(d["extra_args"] or "{}")
        # sampling 子对象展开为独立参数行（如 top-k = 40）
        sampling = extra.pop("sampling", None) if isinstance(extra, dict) else None
        if isinstance(sampling, dict):
            for k, v in sampling.items():
                if v is None or v == "":
                    continue
                lines.append(f"{k.replace('_', '-')} = {v}")
        for k, v in extra.items():
            lines.append(f"{k} = {v}")
        lines.append("")

    content = "\n".join(lines)
    config_path = Path(settings.model_dir) / "config.ini"
    try:
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(content)
        return {"ok": True, "path": str(config_path), "content": content}
    except Exception as e:
        return {"ok": False, "error": str(e), "content": content}


class PresetCreate(BaseModel):
    model_name: str
    backend: str = "sycl-fp16"  # 兼容字段（已忽略：模板后端无关，不再按 backend 分套）
    ctx_size: int = 8192
    temp: float = 0.7
    threads: int = 8
    batch_size: int = 2048
    ubatch_size: int = 512
    parallel: int = 4
    cache_type_k: str = "q8_0"
    cache_type_v: str = "q8_0"
    flash_attn: bool = True
    jinja: bool = True
    n_gpu_layers: int = 99
    mmap: bool = True
    cpu_moe: bool = False
    cpu_moe_layers: int | None = None
    mtp: bool = False
    mtp_model: str = ""
    mtp_n_max: int = 3
    spec_draft_type_k: str = ""
    spec_draft_type_v: str = ""
    device: str = "SYCL0"
    rope_scaling: str = ""
    rope_scale: float | None = None
    yarn_orig_ctx: int | None = None
    reasoning: str = ""
    reasoning_budget: int | None = None
    reasoning_effort: str = ""
    extra_args: dict = {}

    @field_validator(
        "ctx_size", "temp", "threads", "batch_size", "ubatch_size", "parallel",
        "n_gpu_layers", "mtp_n_max", "rope_scale", "yarn_orig_ctx", "reasoning_budget", "cpu_moe_layers", mode="before",
    )
    @classmethod
    def _empty_to_none(cls, v):
        # 前端 el-input-number 清空后可能提交空字符串，在类型解析前归一化为 None 避免 422
        if v == "" or v is None:
            return None
        return v

    @field_validator("rope_scaling", "reasoning", "reasoning_effort", mode="before")
    @classmethod
    def _enum_string_normalize(cls, v):
        # 字符串枚举字段：可能收到布尔值（el-switch 误绑）或空串；'' 是有效关闭值不能归 None
        if v is None:
            return None
        if isinstance(v, bool):
            return "on" if v else ""
        if v == "":
            return ""
        return str(v)


class PresetUpdate(BaseModel):
    ctx_size: int | None = None
    temp: float | None = None
    threads: int | None = None
    batch_size: int | None = None
    ubatch_size: int | None = None
    parallel: int | None = None
    cache_type_k: str | None = None
    cache_type_v: str | None = None
    flash_attn: bool | None = None
    jinja: bool | None = None
    n_gpu_layers: int | None = None
    mmap: bool | None = None
    cpu_moe: bool | None = None
    cpu_moe_layers: int | None = None
    mtp: bool | None = None
    mtp_model: str | None = None
    mtp_n_max: int | None = None
    spec_draft_type_k: str | None = None
    spec_draft_type_v: str | None = None
    device: str | None = None
    rope_scaling: str | None = None
    rope_scale: float | None = None
    yarn_orig_ctx: int | None = None
    reasoning: str | None = None
    reasoning_budget: int | None = None
    reasoning_effort: str | None = None
    extra_args: dict | None = None

    @field_validator(
        "ctx_size", "temp", "threads", "batch_size", "ubatch_size", "parallel",
        "n_gpu_layers", "mtp_n_max", "rope_scale", "yarn_orig_ctx", "reasoning_budget", "cpu_moe_layers", mode="before",
    )
    @classmethod
    def _empty_to_none(cls, v):
        # 前端 el-input-number 清空后可能提交空字符串，在类型解析前归一化为 None 避免 422
        if v == "" or v is None:
            return None
        return v

    @field_validator("rope_scaling", "reasoning", "reasoning_effort", mode="before")
    @classmethod
    def _enum_string_normalize(cls, v):
        # 字符串枚举字段：可能收到布尔值或空串；'' 是有效关闭值不能归 None
        if v is None:
            return None
        if isinstance(v, bool):
            return "on" if v else ""
        if v == "":
            return ""
        return str(v)


@router.get("")
def list_presets():
    """列出所有模型预设（模板后端无关，单套）"""
    with get_conn() as conn:
        rows = conn.execute("SELECT * FROM model_presets ORDER BY model_name").fetchall()
    out = []
    for r in rows:
        d = dict(r)
        d["backend"] = "universal"
        d["flash_attn"] = bool(d["flash_attn"])
        d["jinja"] = bool(d["jinja"])
        d["mmap"] = bool(d.get("mmap", 1))
        d["cpu_moe"] = bool(d.get("cpu_moe", 0))
        d["cpu_moe_layers"] = d.get("cpu_moe_layers") or 0
        d["mtp"] = bool(d.get("mtp", 0))
        d["mtp_model"] = d.get("mtp_model", "")
        d["mtp_n_max"] = d.get("mtp_n_max", 3)
        d["spec_draft_type_k"] = d.get("spec_draft_type_k", "")
        d["spec_draft_type_v"] = d.get("spec_draft_type_v", "")
        d["rope_scaling"] = d.get("rope_scaling", "")
        d["rope_scale"] = d.get("rope_scale")
        d["yarn_orig_ctx"] = d.get("yarn_orig_ctx")
        d["reasoning"] = d.get("reasoning", "")
        d["reasoning_budget"] = d.get("reasoning_budget")
        d["reasoning_effort"] = d.get("reasoning_effort", "")
        d["device"] = _normalize_device(d.get("device"))
        d["extra_args"] = json.loads(d["extra_args"] or "{}")
        out.append(d)
    return out


@router.post("")
def create_preset(body: PresetCreate):
    """创建模型预设（单套，后端无关）"""
    with get_conn() as conn:
        dup = conn.execute(
            "SELECT id FROM model_presets WHERE model_name=?",
            (body.model_name,),
        ).fetchone()
        if dup:
            raise HTTPException(400, f"模型 {body.model_name} 的预设已存在")
        conn.execute(
            "INSERT INTO model_presets (model_name, ctx_size, temp, threads, batch_size, ubatch_size, "
            "parallel, cache_type_k, cache_type_v, flash_attn, jinja, n_gpu_layers, mmap, cpu_moe, cpu_moe_layers, mtp, mtp_model, mtp_n_max, spec_draft_type_k, spec_draft_type_v, device, rope_scaling, rope_scale, yarn_orig_ctx, reasoning, reasoning_budget, reasoning_effort, extra_args, created_at, updated_at) "
            "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (body.model_name, body.ctx_size, body.temp, body.threads, body.batch_size,
             body.ubatch_size, body.parallel, body.cache_type_k, body.cache_type_v,
             1 if body.flash_attn else 0, 1 if body.jinja else 0, body.n_gpu_layers,
             1 if body.mmap else 0, 1 if body.cpu_moe else 0, body.cpu_moe_layers or 0, 1 if body.mtp else 0, body.mtp_model or "",
             body.mtp_n_max or 3, body.spec_draft_type_k or "", body.spec_draft_type_v or "",
             _normalize_device(body.device), body.rope_scaling or "",
             body.rope_scale, body.yarn_orig_ctx, body.reasoning or "", body.reasoning_budget,
             body.reasoning_effort or "", json.dumps(body.extra_args), now(), now()),
        )
    # 同步生成 config.ini（router 重启后生效）
    _write_config_ini()
    return {"ok": True, "model_name": body.model_name, "backend": "universal"}


@router.put("/{pid}")
def update_preset(pid: int, body: PresetUpdate):
    """更新模型预设"""
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM model_presets WHERE id=?", (pid,)).fetchone()
        if not row:
            raise HTTPException(404, "预设不存在")
        d = dict(row)
        updates = {}
        for field in ["ctx_size", "temp", "threads", "batch_size", "ubatch_size", "parallel",
                       "cache_type_k", "cache_type_v", "n_gpu_layers", "device"]:
            v = getattr(body, field, None)
            if v is not None:
                updates[field] = _normalize_device(v) if field == "device" else v
        if body.flash_attn is not None:
            updates["flash_attn"] = 1 if body.flash_attn else 0
        if body.jinja is not None:
            updates["jinja"] = 1 if body.jinja else 0
        if body.mmap is not None:
            updates["mmap"] = 1 if body.mmap else 0
        if body.cpu_moe is not None:
            updates["cpu_moe"] = 1 if body.cpu_moe else 0
        if body.cpu_moe_layers is not None:
            updates["cpu_moe_layers"] = body.cpu_moe_layers
        if body.mtp is not None:
            updates["mtp"] = 1 if body.mtp else 0
        if body.mtp_model is not None:
            updates["mtp_model"] = body.mtp_model
        if body.mtp_n_max is not None:
            updates["mtp_n_max"] = body.mtp_n_max
        # spec_draft_type_k/v：空串也是有效值（''=不传，用默认 f16），区分 None（不修改）与 ''（清空）
        if body.spec_draft_type_k is not None:
            updates["spec_draft_type_k"] = body.spec_draft_type_k
        if body.spec_draft_type_v is not None:
            updates["spec_draft_type_v"] = body.spec_draft_type_v
        # rope_scaling：空串也是有效值（''=关闭），需区分 None（不修改）与 ''（清空）
        if body.rope_scaling is not None:
            updates["rope_scaling"] = body.rope_scaling
            if body.rope_scaling == "":
                # 关闭缩放时联动清空 scale/orig（否则残留 0/旧值，面板显示像没关干净）
                updates["rope_scale"] = None
                updates["yarn_orig_ctx"] = None
            else:
                # 开启/切换缩放方法时，scale/orig 正常更新
                if body.rope_scale is not None:
                    updates["rope_scale"] = body.rope_scale
                if body.yarn_orig_ctx is not None:
                    updates["yarn_orig_ctx"] = body.yarn_orig_ctx
        else:
            if body.rope_scale is not None:
                updates["rope_scale"] = body.rope_scale
            if body.yarn_orig_ctx is not None:
                updates["yarn_orig_ctx"] = body.yarn_orig_ctx
        # reasoning：空串也是有效值（''=不配置），区分 None（不修改）与 ''（清空）
        if body.reasoning is not None:
            updates["reasoning"] = body.reasoning
            if body.reasoning == "":
                # 关闭思考时联动清空 budget 与 effort
                updates["reasoning_budget"] = None
                updates["reasoning_effort"] = ""
            else:
                if body.reasoning_budget is not None:
                    updates["reasoning_budget"] = body.reasoning_budget
                # 思考强度：空串也是有效值（''=用模板默认），区分 None（不修改）与 ''（清空）
                if body.reasoning_effort is not None:
                    updates["reasoning_effort"] = body.reasoning_effort
        else:
            if body.reasoning_budget is not None:
                updates["reasoning_budget"] = body.reasoning_budget
            if body.reasoning_effort is not None:
                updates["reasoning_effort"] = body.reasoning_effort
        if body.extra_args is not None:
            updates["extra_args"] = json.dumps(body.extra_args)

        if updates:
            sets = ", ".join(f"{k}=?" for k in updates)
            vals = list(updates.values()) + [now(), pid]
            conn.execute(f"UPDATE model_presets SET {sets}, updated_at=? WHERE id=?", vals)

    # 同步生成 config.ini（router 重启后生效）
    _write_config_ini()
    return {"ok": True}


@router.delete("/{pid}")
def delete_preset(pid: int):
    """删除模型预设"""
    with get_conn() as conn:
        conn.execute("DELETE FROM model_presets WHERE id=?", (pid,))
    # 同步重建 config.ini（移除对应 section）
    _write_config_ini()
    return {"ok": True}


@router.post("/generate-config")
def generate_config_ini():
    """根据所有预设生成 config.ini 文件内容（供 llama-server --models-preset 使用）"""
    return _write_config_ini()


# ---------- 显存估算（M9） ----------

class EstimateRequest(BaseModel):
    model_path: str
    ctx_size: int = 8192
    batch_size: int = 2048
    ubatch_size: int = 512
    parallel: int = 4
    cache_type_k: str = "q8_0"
    cache_type_v: str = "q8_0"
    n_gpu_layers: int = 99
    flash_attn: bool = True
    mmproj: str = ""


# KV cache 每元素字节（近似）：f16=2, q8_0≈1.0625, q5_0≈0.6875, q4_0≈0.5625, q4_1≈0.625
_KV_BYTES = {
    "f16": 2.0, "f32": 4.0, "q8_0": 1.0625, "q5_0": 0.6875, "q5_1": 0.75,
    "q4_0": 0.5625, "q4_1": 0.625, "iq4_nl": 0.5625, "bf16": 2.0,
}
# 计算图 buffer 系数（经验值）：每层每 batch 每 embd 约 2 字节（f16 激活）
_GRAPH_COEF = 2.0


@router.post("/estimate-memory")
def estimate_memory(body: EstimateRequest):
    """估算模型加载显存占用（llama.cpp 口径）"""
    from pathlib import Path
    from app.routers.models import parse_gguf_meta, _scan_models

    mp = body.model_path
    if not mp.startswith("/"):
        mp = f"/models/{mp.lstrip('/')}"
    path = Path(mp)
    if not path.exists():
        raise HTTPException(404, f"模型文件不存在: {mp}")

    meta = parse_gguf_meta(path)
    if not meta or not meta.get("file_size_bytes"):
        raise HTTPException(400, "无法解析 GGUF 元信息（文件可能损坏或非 GGUF）")

    file_size = meta["file_size_bytes"]
    n_layer = meta.get("n_layer") or 0
    # 混合架构（Mamba+Attention 交替）用实际 attention 层数算 KV
    attn_layers = meta.get("attn_layers") or n_layer
    n_head_kv = meta.get("n_head_kv") or 0
    head_dim = meta.get("head_dim") or 0
    n_embd = meta.get("n_embd") or 0
    arch = meta.get("architecture", "")

    # 1) 模型权重：mmap 全量映射，GPU 占用按 GPU 层数占比
    #    （n_gpu_layers>=层数 或 99 表示全量 GPU）
    gpu_layers = body.n_gpu_layers
    if gpu_layers >= n_layer or gpu_layers >= 99:
        gpu_ratio = 1.0
    elif n_layer > 0:
        gpu_ratio = gpu_layers / n_layer
    else:
        gpu_ratio = 1.0
    model_bytes = file_size * gpu_ratio

    # 2) KV cache：n_ctx × attn_layers × n_head_kv × head_dim × 2(K+V) × bytes
    kv_b_k = _KV_BYTES.get(body.cache_type_k, 1.0625)
    kv_b_v = _KV_BYTES.get(body.cache_type_v, 1.0625)
    if attn_layers and n_head_kv and head_dim:
        kv_bytes = body.ctx_size * attn_layers * n_head_kv * head_dim * (kv_b_k + kv_b_v)
    else:
        kv_bytes = 0

    # 3) compute buffer：激活/计算图（每层 batch 粒度）
    if n_layer and n_embd and body.batch_size:
        graph_bytes = (n_layer + 1) * body.batch_size * n_embd * _GRAPH_COEF
    else:
        graph_bytes = 0

    # 4) mmproj（视觉模型）
    mmproj_bytes = 0
    if body.mmproj:
        try:
            mm_path = Path(body.mmproj)
            if not mm_path.is_absolute():
                mm_path = Path("/models") / body.mmproj.lstrip("/")
            if mm_path.exists():
                mmproj_bytes = mm_path.stat().st_size
        except Exception:
            pass

    # 5) 系统余量（驱动/上下文开销）
    overhead_bytes = 512 * 1024 * 1024

    total_bytes = model_bytes + kv_bytes + graph_bytes + mmproj_bytes + overhead_bytes

    def _gib(b):
        return round(b / 1024 / 1024 / 1024, 2)

    return {
        "model": mp,
        "architecture": arch,
        "quantization": meta.get("quantization", ""),
        "parts": {
            "model_weights": _gib(model_bytes),
            "kv_cache": _gib(kv_bytes),
            "compute_graph": _gib(graph_bytes),
            "mmproj": _gib(mmproj_bytes),
            "overhead": _gib(overhead_bytes),
        },
        "total_gib": _gib(total_bytes),
        "details": {
            "file_size_gib": _gib(file_size),
            "n_layer": n_layer,
            "attn_layers": attn_layers,
            "n_head_kv": n_head_kv,
            "head_dim": head_dim,
            "n_embd": n_embd,
            "ctx_size": body.ctx_size,
            "gpu_layers_ratio": round(gpu_ratio, 3),
            "kv_bytes_per_token": round((kv_b_k + kv_b_v) * attn_layers * n_head_kv * head_dim / 1024 / 1024, 2) if (attn_layers and n_head_kv and head_dim) else 0,
        },
        "formula_note": "模型权重(按GPU层数占比) + KV Cache + 计算图 + mmproj + 512MB余量",
    }
