"""模型预设配置 API - 管理不同模型的启动参数预设"""
import json
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from app.database import get_conn, now
from app.config import settings

router = APIRouter()


def _normalize_device(v) -> str:
    """将旧值(0/1)映射为 SYCL0/SYCL1，已含 SYCL 前缀的原样保留"""
    if not v:
        return "SYCL0"
    s = str(v)
    if s.startswith("SYCL"):
        return s
    if s.isdigit():
        return f"SYCL{s}"
    return "SYCL0"


def _find_mmproj(model_name: str) -> str:
    """在模型 gguf 同目录中查找 mmproj 文件（mmproj*.gguf）
    通过 services 表 model_path 定位模型文件所在目录，返回绝对路径或空串"""
    from pathlib import Path as _P
    base = _P(settings.model_dir)
    if not base.exists():
        return ""
    # 1) 通过 services 表拿到 model_path，找同目录
    search_dirs = []
    try:
        with get_conn() as conn:
            row = conn.execute("SELECT model_path FROM services WHERE name=?", (model_name,)).fetchone()
        if row and row["model_path"]:
            mp = row["model_path"].replace("/models/", "")
            p = base / mp
            search_dirs.append(p.parent if p.suffix else p)
    except Exception:
        pass
    # 2) 兜底：模型名是 gguf 文件名时，其目录 = base；否则扫描子目录
    if not search_dirs:
        if base.glob(f"{model_name}.gguf"):
            search_dirs.append(base)
        else:
            for d in base.iterdir():
                if d.is_dir() and d.name in model_name:
                    search_dirs.append(d)
    seen = set()
    for d in search_dirs:
        if not d.exists() or d in seen:
            continue
        seen.add(d)
        for p in sorted(d.glob("mmproj*.gguf")):
            return str(p)
    return ""


def _write_config_ini() -> dict:
    """从 DB 全量生成 config.ini 并写入模型目录（幂等：先清空再重建）
    返回 {"ok": bool, "path": str, "content": str, "error": str?}
    """
    from pathlib import Path

    with get_conn() as conn:
        rows = conn.execute("SELECT * FROM model_presets ORDER BY model_name").fetchall()
        # 预设名 -> 模型文件路径（services 表），供 config.ini 的 model= 行
        path_rows = conn.execute("SELECT name, model_path FROM services").fetchall()
        path_by_name = {r["name"]: r["model_path"] for r in path_rows}

    lines = ["# llama-server router model presets", "# Auto-generated by llama-studio", ""]
    for r in rows:
        d = dict(r)
        lines.append(f"[{d['model_name']}]")
        # model= 必须显式绑定文件路径，llama.cpp 才会应用该段的 ctx/参数到对应模型
        mp = path_by_name.get(d["model_name"])
        if mp:
            lines.append(f"model = {mp}")
        lines.append(f"ctx-size = {d['ctx_size']}")
        lines.append(f"temp = {d['temp']}")
        lines.append(f"threads = {d['threads']}")
        lines.append(f"batch-size = {d['batch_size']}")
        lines.append(f"ubatch-size = {d['ubatch_size']}")
        lines.append(f"parallel = {d['parallel']}")
        lines.append(f"cache-type-k = {d['cache_type_k']}")
        lines.append(f"cache-type-v = {d['cache_type_v']}")
        if d["flash_attn"]:
            lines.append("flash-attn = on")
        if d["jinja"]:
            lines.append("jinja = on")
        if not d.get("mmap", 1):
            lines.append("no-mmap = on")
        lines.append(f"n-gpu-layers = {d['n_gpu_layers']}")
        dev = _normalize_device(d.get("device"))
        lines.append(f"device = {dev}")
        # 自动检测 mmproj 并写入（多模态投影文件）
        mmproj = _find_mmproj(d["model_name"])
        if mmproj:
            lines.append(f"mmproj = {mmproj}")
        extra = json.loads(d["extra_args"] or "{}")
        # sampling 子对象展开为独立参数行（如 top-k = 40）
        sampling = extra.pop("sampling", None) if isinstance(extra, dict) else None
        if isinstance(sampling, dict):
            for k, v in sampling.items():
                if v is None or v == "":
                    continue
                lines.append(f"{k.replace('_', '-')} = {v}")
        for k, v in extra.items():
            lines.append(f"{k} = {v}")
        lines.append("")

    content = "\n".join(lines)
    config_path = Path(settings.model_dir) / "config.ini"
    try:
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(content)
        return {"ok": True, "path": str(config_path), "content": content}
    except Exception as e:
        return {"ok": False, "error": str(e), "content": content}


class PresetCreate(BaseModel):
    model_name: str
    ctx_size: int = 8192
    temp: float = 0.7
    threads: int = 8
    batch_size: int = 2048
    ubatch_size: int = 512
    parallel: int = 4
    cache_type_k: str = "q8_0"
    cache_type_v: str = "q8_0"
    flash_attn: bool = False
    jinja: bool = True
    n_gpu_layers: int = 99
    mmap: bool = True
    device: str = "SYCL0"
    extra_args: dict = {}


class PresetUpdate(BaseModel):
    ctx_size: int | None = None
    temp: float | None = None
    threads: int | None = None
    batch_size: int | None = None
    ubatch_size: int | None = None
    parallel: int | None = None
    cache_type_k: str | None = None
    cache_type_v: str | None = None
    flash_attn: bool | None = None
    jinja: bool | None = None
    n_gpu_layers: int | None = None
    mmap: bool | None = None
    device: str | None = None
    extra_args: dict | None = None


@router.get("")
def list_presets():
    """列出所有模型预设"""
    with get_conn() as conn:
        rows = conn.execute("SELECT * FROM model_presets ORDER BY model_name").fetchall()
    out = []
    for r in rows:
        d = dict(r)
        d["flash_attn"] = bool(d["flash_attn"])
        d["jinja"] = bool(d["jinja"])
        d["mmap"] = bool(d.get("mmap", 1))
        d["device"] = _normalize_device(d.get("device"))
        d["extra_args"] = json.loads(d["extra_args"] or "{}")
        out.append(d)
    return out


@router.post("")
def create_preset(body: PresetCreate):
    """创建模型预设"""
    with get_conn() as conn:
        dup = conn.execute("SELECT id FROM model_presets WHERE model_name=?", (body.model_name,)).fetchone()
        if dup:
            raise HTTPException(400, f"模型 {body.model_name} 的预设已存在")
        conn.execute(
            "INSERT INTO model_presets (model_name, ctx_size, temp, threads, batch_size, ubatch_size, "
            "parallel, cache_type_k, cache_type_v, flash_attn, jinja, n_gpu_layers, mmap, device, extra_args, created_at, updated_at) "
            "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (body.model_name, body.ctx_size, body.temp, body.threads, body.batch_size,
             body.ubatch_size, body.parallel, body.cache_type_k, body.cache_type_v,
             1 if body.flash_attn else 0, 1 if body.jinja else 0, body.n_gpu_layers,
             1 if body.mmap else 0, _normalize_device(body.device), json.dumps(body.extra_args), now(), now()),
        )
    # 同步生成 config.ini（router 重启后生效）
    _write_config_ini()
    return {"ok": True, "model_name": body.model_name}


@router.put("/{pid}")
def update_preset(pid: int, body: PresetUpdate):
    """更新模型预设"""
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM model_presets WHERE id=?", (pid,)).fetchone()
        if not row:
            raise HTTPException(404, "预设不存在")
        d = dict(row)
        updates = {}
        for field in ["ctx_size", "temp", "threads", "batch_size", "ubatch_size", "parallel",
                       "cache_type_k", "cache_type_v", "n_gpu_layers", "device"]:
            v = getattr(body, field, None)
            if v is not None:
                updates[field] = _normalize_device(v) if field == "device" else v
        if body.flash_attn is not None:
            updates["flash_attn"] = 1 if body.flash_attn else 0
        if body.jinja is not None:
            updates["jinja"] = 1 if body.jinja else 0
        if body.mmap is not None:
            updates["mmap"] = 1 if body.mmap else 0
        if body.extra_args is not None:
            updates["extra_args"] = json.dumps(body.extra_args)

        if updates:
            sets = ", ".join(f"{k}=?" for k in updates)
            vals = list(updates.values()) + [now(), pid]
            conn.execute(f"UPDATE model_presets SET {sets}, updated_at=? WHERE id=?", vals)

    # 同步生成 config.ini（router 重启后生效）
    _write_config_ini()
    return {"ok": True}


@router.delete("/{pid}")
def delete_preset(pid: int):
    """删除模型预设"""
    with get_conn() as conn:
        conn.execute("DELETE FROM model_presets WHERE id=?", (pid,))
    # 同步重建 config.ini（移除对应 section）
    _write_config_ini()
    return {"ok": True}


@router.post("/generate-config")
def generate_config_ini():
    """根据所有预设生成 config.ini 文件内容（供 llama-server --models-preset 使用）"""
    return _write_config_ini()
