"""模型预设配置 API - 管理不同模型的启动参数预设"""
import json
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from app.database import get_conn, now

router = APIRouter()


class PresetCreate(BaseModel):
    model_name: str
    ctx_size: int = 8192
    temp: float = 0.7
    threads: int = 8
    batch_size: int = 2048
    ubatch_size: int = 512
    parallel: int = 4
    cache_type_k: str = "q8_0"
    cache_type_v: str = "q8_0"
    flash_attn: bool = True
    jinja: bool = True
    n_gpu_layers: int = 99
    extra_args: dict = {}


class PresetUpdate(BaseModel):
    ctx_size: int | None = None
    temp: float | None = None
    threads: int | None = None
    batch_size: int | None = None
    ubatch_size: int | None = None
    parallel: int | None = None
    cache_type_k: str | None = None
    cache_type_v: str | None = None
    flash_attn: bool | None = None
    jinja: bool | None = None
    n_gpu_layers: int | None = None
    extra_args: dict | None = None


@router.get("")
def list_presets():
    """列出所有模型预设"""
    with get_conn() as conn:
        rows = conn.execute("SELECT * FROM model_presets ORDER BY model_name").fetchall()
    out = []
    for r in rows:
        d = dict(r)
        d["flash_attn"] = bool(d["flash_attn"])
        d["jinja"] = bool(d["jinja"])
        d["extra_args"] = json.loads(d["extra_args"] or "{}")
        out.append(d)
    return out


@router.post("")
def create_preset(body: PresetCreate):
    """创建模型预设"""
    with get_conn() as conn:
        dup = conn.execute("SELECT id FROM model_presets WHERE model_name=?", (body.model_name,)).fetchone()
        if dup:
            raise HTTPException(400, f"模型 {body.model_name} 的预设已存在")
        conn.execute(
            "INSERT INTO model_presets (model_name, ctx_size, temp, threads, batch_size, ubatch_size, "
            "parallel, cache_type_k, cache_type_v, flash_attn, jinja, n_gpu_layers, extra_args, created_at, updated_at) "
            "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (body.model_name, body.ctx_size, body.temp, body.threads, body.batch_size,
             body.ubatch_size, body.parallel, body.cache_type_k, body.cache_type_v,
             1 if body.flash_attn else 0, 1 if body.jinja else 0, body.n_gpu_layers,
             json.dumps(body.extra_args), now(), now()),
        )
    return {"ok": True, "model_name": body.model_name}


@router.put("/{pid}")
def update_preset(pid: int, body: PresetUpdate):
    """更新模型预设"""
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM model_presets WHERE id=?", (pid,)).fetchone()
        if not row:
            raise HTTPException(404, "预设不存在")
        d = dict(row)
        updates = {}
        for field in ["ctx_size", "temp", "threads", "batch_size", "ubatch_size", "parallel",
                       "cache_type_k", "cache_type_v", "n_gpu_layers"]:
            v = getattr(body, field, None)
            if v is not None:
                updates[field] = v
        if body.flash_attn is not None:
            updates["flash_attn"] = 1 if body.flash_attn else 0
        if body.jinja is not None:
            updates["jinja"] = 1 if body.jinja else 0
        if body.extra_args is not None:
            updates["extra_args"] = json.dumps(body.extra_args)

        if updates:
            sets = ", ".join(f"{k}=?" for k in updates)
            vals = list(updates.values()) + [now(), pid]
            conn.execute(f"UPDATE model_presets SET {sets}, updated_at=? WHERE id=?", vals)

    return {"ok": True}


@router.delete("/{pid}")
def delete_preset(pid: int):
    """删除模型预设"""
    with get_conn() as conn:
        conn.execute("DELETE FROM model_presets WHERE id=?", (pid,))
    return {"ok": True}


@router.post("/generate-config")
def generate_config_ini():
    """根据所有预设生成 config.ini 文件内容（供 llama-server --models-preset 使用）"""
    with get_conn() as conn:
        rows = conn.execute("SELECT * FROM model_presets ORDER BY model_name").fetchall()

    lines = ["# llama-server router model presets", "# Auto-generated by llama-studio", ""]
    for r in rows:
        d = dict(r)
        lines.append(f"[{d['model_name']}]")
        lines.append(f"ctx-size = {d['ctx_size']}")
        lines.append(f"temp = {d['temp']}")
        lines.append(f"threads = {d['threads']}")
        lines.append(f"batch-size = {d['batch_size']}")
        lines.append(f"ubatch-size = {d['ubatch_size']}")
        lines.append(f"parallel = {d['parallel']}")
        lines.append(f"cache-type-k = {d['cache_type_k']}")
        lines.append(f"cache-type-v = {d['cache_type_v']}")
        if d["flash_attn"]:
            lines.append("flash-attn = on")
        if d["jinja"]:
            lines.append("jinja = on")
        lines.append(f"n-gpu-layers = {d['n_gpu_layers']}")
        extra = json.loads(d["extra_args"] or "{}")
        for k, v in extra.items():
            lines.append(f"{k} = {v}")
        lines.append("")

    content = "\n".join(lines)
    # 写入 /models/config.ini
    from app.config import settings
    from pathlib import Path
    config_path = Path(settings.model_dir) / "config.ini"
    try:
        config_path.write_text(content)
        return {"ok": True, "path": str(config_path), "content": content}
    except Exception as e:
        return {"ok": False, "error": str(e), "content": content}
